env:
  browser: true
  es6: true
globals:
  process: false
extends: [eslint:recommended, plugin:react/recommended]
plugins: [react]

parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module

rules:
  indent: [error, 2]
  quotes: [warn, single]
  semi: [error, never]
  comma-dangle: [warn, only-multiline]
  no-console: [off]
  react/prop-types: [error, {skipUndeclared: true}]