env:
  browser: true
  es6: true
extends: 'eslint:recommended'
parser: "babel-eslint"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  indent: [error, 2]
  quotes: [warn, single]
  semi: [error, never]
  comma-dangle: [warn, always]